# Theme settings
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


# Site wide configuration
title: "Quantitative Genetic Evolutionary Ecology"
subtitle: "Variance is the spice of life"
description: "The Wolak Research Group at Auburn University."
logo: Warlak_siteLogoCard128px.png # 128x128 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en_US
#url: https://qgevoeco.github.io
url: https://qgevoeco.com
feed:
  path: atom.xml
search : true
search_full_content: true
search_provider: lunr # (default), algolia, google
lunr:
  search_within_pages: true
  

# Site owner
owner:
  name: Matthew Wolak
  avatar: bio-WolakMatthew.png # 160x160 px image for author byline
  bio: "Evolutionary Ecologist and Quantitative Geneticist"
  location: "Auburn, AL"
  email: terps@auburn.edu
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:terps@auburn.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/qgevoeco"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com"
      
  disqus-shortname: qgevoeco

picture:
  source: images/_fullsize
  output: images

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/qgevoeco"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      #url:
      
      
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-gist
  - jekyll-feed
  - jekyll-avatar
  - jekyll/scholar
  - jekyll-sitemap

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Scholar settings
scholar:
  style: peerj
  locale: en
  sort_by: year
  order: descending
  bibtex_filters: latex
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib-link
  replace_strings: true
  join_strings:    true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"



# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      
