# Site wide configuration

title: "Quantitative Genetic Evolutionary Ecology"
description: "The Wolak Research Group at Auburn University."
logo: Warlak_siteLogoCard128px.png # 128x128 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en_US
baseurl: ""
#url: https://qgevoeco.github.io
url: https://qgevoeco.com
feed:
  path: atom.xml

# Jekyll configuration
permalink: /:categories/:title/
sass:
  sass_dir: _sass
  style: compressed
kramdown:
  toc_levels: 1..4
highlighter: rouge
plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-avatar
  - jekyll/scholar
  - jekyll-sitemap

# Scholar settings
scholar:
  style: peerj
  locale: en
  sort_by: year
  order: descending
  bibtex_filters: latex
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib-link
  replace_strings: true
  join_strings:    true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"

# Site owner
owner:
  name: Matthew Wolak
  email: terps@auburn.edu
  twitter:
  github: matthewwolak
  bio: "Evolutionary Ecologist and Quantitative Geneticist"
  avatar: bio-WolakMatthew.png # 160x160 px image for author byline
  disqus-shortname: qgevoeco
  instagram: qgevoeco

# Site Footer
##TODO See how done in minimal-mistakes
### will need to add footer.html file https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/footer.html
#### and then add this to each page
#footer:
#  links:
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
      # url:
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/qgevoeco"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/qgevoeco"


picture:
  source: images/_fullsize
  output: images


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

encoding: utf-8
timezone: America/Chicago
